# Docker image that will have git and python3 installed.
# For the client side, python modules used are requests and time, which are installed by default.

FROM ubuntu:latest
RUN apt -y update && apt -y install git python3
